# Generated by Django 4.0.1 on 2022-08-06 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assignproject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignuser', models.CharField(max_length=255)),
                ('assignproject', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('ProjectName', models.CharField(default='', max_length=255)),
                ('Companyname', models.CharField(default='', max_length=255)),
                ('skills', models.CharField(default='', max_length=255)),
                ('Description', models.TextField(default='')),
                ('Date', models.DateField(auto_now=True)),
                ('Duration', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default=True, max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateField(auto_now=True)),
                ('Image', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='business_enquire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=255)),
                ('company_subject', models.CharField(max_length=255)),
                ('company_description', models.TextField()),
                ('company_contact', models.CharField(max_length=10)),
                ('company_date', models.DateField(auto_now=True)),
                ('company_token', models.CharField(max_length=255)),
                ('company_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='user_enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('token', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IS_APPLICANT_A_DEPARTMENTAL_CANDIDATE', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('IS_APPLICANT_GATE_QUALIFIED', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True)),
                ('GATE_SCORE_YEAR', models.CharField(blank=True, max_length=6, null=True)),
                ('GATE_SCORE', models.PositiveIntegerField(blank=True, null=True)),
                ('GATE_ROLL_NO', models.PositiveIntegerField(blank=True, null=True)),
                ('AADHAAR_CARD_NO', models.CharField(max_length=12)),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('MIDDLE_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('FATHER_NAME', models.CharField(max_length=50)),
                ('MOTHER_NAME', models.CharField(max_length=50)),
                ('DATE_OF_BIRTH', models.DateField(blank=True, null=True)),
                ('CANDIDATE_GENDER', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True)),
                ('IS_CANDIDATES_MARRIED', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True)),
                ('HUSBAND_WIFE_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('NUMBER_OF_SURVIVING_CHILDREN', models.PositiveIntegerField(blank=True, null=True)),
                ('LAST_CHILD_DATE_OF_BIRTH', models.DateField(blank=True, null=True)),
                ('IS_THE_LAST_CHILD_TWIN', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True)),
                ('CANDIDATE_IS_A_WIDOW_DIVORCED_ABANDONED_WOMAN', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True)),
                ('USER_CODE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
