# Generated by Django 4.0.1 on 2022-08-08 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NATIVE_OF_MADHYA_PRADESH', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True)),
                ('CATEGORY', models.CharField(choices=[('UR', 'UR'), ('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('EWS', 'EWS')], max_length=3, null=True)),
                ('BELONGS_TO_CREAMY_LAYER', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True)),
                ('DISABILITY_CERTIFICATE', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True)),
                ('MINIMUM_40_PERCENT_DISABILITY', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True)),
                ('TYPE_OF_DISABILITY', models.CharField(choices=[('Fractured(OH)', 'Fractured(OH)'), ('Vision Impaired(VH)', 'Vision Impaired(VH)'), ('Hearing Impairment(HH)', 'Hearing Impairment(HH)'), ('Multiple Disabilities(MD)', 'Multiple Disabilities(MD)')], max_length=255, null=True)),
                ('PERCENTAGE_OF_DISABILITY', models.CharField(blank=True, default=' ', max_length=5, null=True)),
                ('CANDIDATE_PUNISHED', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True)),
                ('DEBARRED_PERIOD_FROM_ANY_EXAMINATION', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True)),
                ('SERVING_IN_THE_GOVERNMENT', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True)),
                ('LIVE_REGISTRATION_IN_THE_EMPLOYMENT_OFFICE', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255, null=True)),
                ('USER_CODE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
