# Generated by Django 4.0.1 on 2022-08-08 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Applicant', '0003_educationdetails_graduation_passing_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PRESENT_STATE', models.CharField(blank=True, max_length=255, null=True)),
                ('PRESENT_DISTRICT', models.CharField(blank=True, max_length=255, null=True)),
                ('PRESENT_PIN_CODE', models.CharField(blank=True, max_length=255, null=True)),
                ('PRESENT_LAND_MARK', models.CharField(blank=True, max_length=255, null=True)),
                ('MOBILE_NUMBER', models.CharField(blank=True, max_length=255, null=True)),
                ('EMAIL_ID', models.EmailField(blank=True, max_length=255, null=True)),
                ('PERMANENT_STATE', models.CharField(blank=True, max_length=255, null=True)),
                ('PERMANENT_DISTRICT', models.CharField(blank=True, max_length=255, null=True)),
                ('PERMANENT_PIN_CODE', models.CharField(blank=True, max_length=255, null=True)),
                ('PERMANENT_LAND_MARK', models.CharField(blank=True, max_length=255, null=True)),
                ('PERMANENT_ADDRESS', models.CharField(blank=True, max_length=255, null=True)),
                ('USER_CODE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
