# Generated by Django 4.0.1 on 2022-08-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0004_addressdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressdetail',
            name='PRESENT_ADDRESS',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
