# Generated by Django 4.0.1 on 2022-08-10 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Applicant', '0006_bankdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HIGH_SCHOOL', models.FileField(upload_to='PDF/HIGH_SCHOOL')),
                ('HSSC', models.FileField(upload_to='PDF/HSSC')),
                ('GRADUATION_MARKSHEET', models.FileField(upload_to='PDF/GRADUATION_MARKSHEET')),
                ('POST_GRADUATION', models.FileField(upload_to='PDF/HIGH_SCHOOL')),
                ('AADHAAR_CARD', models.FileField(upload_to='PDF/POST_GRADUATION')),
                ('CAST_CERTIFICATE', models.FileField(upload_to='PDF/CAST_CERTIFICATE')),
                ('GATE_SCORECARD', models.FileField(upload_to='PDF/GATE_SCORECARD')),
                ('DEPARTMENTAL_NOC', models.FileField(blank=True, null=True, upload_to='PDF/DEPARTMENTAL_NOC')),
                ('USER_CODE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
