# Generated by Django 4.0.1 on 2022-08-10 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Applicant', '0007_documentupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceFilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CHOICE_1', models.CharField(choices=[('Asst. Engineer (Electrical)', 'Asst. Engineer (Electrical)'), ('Asst. Engineer (Mechanical)', 'Asst. Engineer (Mechanical)'), ('Asst. Engineer (Civil)', 'Asst. Engineer (Civil)'), ('Asst. Engineer (IT)', 'Asst. Engineer (IT)')], max_length=255)),
                ('CHOICE_2', models.CharField(blank=True, choices=[('Asst. Engineer (Electrical)', 'Asst. Engineer (Electrical)'), ('Asst. Engineer (Mechanical)', 'Asst. Engineer (Mechanical)'), ('Asst. Engineer (Civil)', 'Asst. Engineer (Civil)'), ('Asst. Engineer (IT)', 'Asst. Engineer (IT)')], max_length=255, null=True)),
                ('CHOICE_3', models.CharField(blank=True, choices=[('Asst. Engineer (Electrical)', 'Asst. Engineer (Electrical)'), ('Asst. Engineer (Mechanical)', 'Asst. Engineer (Mechanical)'), ('Asst. Engineer (Civil)', 'Asst. Engineer (Civil)'), ('Asst. Engineer (IT)', 'Asst. Engineer (IT)')], max_length=255, null=True)),
                ('CHOICE_4', models.CharField(blank=True, choices=[('Asst. Engineer (Electrical)', 'Asst. Engineer (Electrical)'), ('Asst. Engineer (Mechanical)', 'Asst. Engineer (Mechanical)'), ('Asst. Engineer (Civil)', 'Asst. Engineer (Civil)'), ('Asst. Engineer (IT)', 'Asst. Engineer (IT)')], max_length=255, null=True)),
                ('CHOICE_5', models.CharField(blank=True, choices=[('Asst. Engineer (Electrical)', 'Asst. Engineer (Electrical)'), ('Asst. Engineer (Mechanical)', 'Asst. Engineer (Mechanical)'), ('Asst. Engineer (Civil)', 'Asst. Engineer (Civil)'), ('Asst. Engineer (IT)', 'Asst. Engineer (IT)')], max_length=255, null=True)),
                ('USER_CODE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
