# Generated by Django 4.0.1 on 2022-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0008_choicefilling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_1',
            field=models.CharField(choices=[('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_2',
            field=models.CharField(blank=True, choices=[('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_3',
            field=models.CharField(blank=True, choices=[('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_4',
            field=models.CharField(blank=True, choices=[('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_5',
            field=models.CharField(blank=True, choices=[('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetail',
            name='CANDIDATE_GENDER',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=55, null=True),
        ),
    ]
