# Generated by Django 4.0.1 on 2022-08-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0012_alter_finaldatatable_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldetail',
            name='CANDIDATE_IS_A_WIDOW_DIVORCED_ABANDONED_WOMAN',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='HUSBAND_WIFE_NAME',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='IS_CANDIDATES_MARRIED',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='IS_THE_LAST_CHILD_TWIN',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='LAST_CHILD_DATE_OF_BIRTH',
        ),
        migrations.RemoveField(
            model_name='personaldetail',
            name='NUMBER_OF_SURVIVING_CHILDREN',
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='CANDIDATE_IS_A_WIDOW_DIVORCED_ABANDONED_WOMAN',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='HUSBAND_WIFE_NAME',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='IS_CANDIDATES_MARRIED',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='IS_THE_LAST_CHILD_TWIN',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='LAST_CHILD_DATE_OF_BIRTH',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='NUMBER_OF_SURVIVING_CHILDREN',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
