# Generated by Django 4.0.1 on 2022-08-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0014_otherdetail_inter_caste_marriage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='POST_APPLIED_FOR',
            field=models.CharField(blank=True, choices=[('Asst. Engineer (Electrical)', 'Asst. Engineer (Electrical)'), ('Asst. Engineer (Mechanical)', 'Asst. Engineer (Mechanical)'), ('Asst. Engineer (Civil)', 'Asst. Engineer (Civil)'), ('Asst. Engineer (IT)', 'Asst. Engineer (IT)')], max_length=55, null=True),
        ),
    ]
