# Generated by Django 4.0.1 on 2022-09-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0015_personaldetail_post_applied_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_amount_debit', models.CharField(default=0, max_length=100)),
                ('txnid', models.CharField(blank=True, max_length=500, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('addedon', models.DateTimeField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('hash_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('PG_TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_ref_num', models.CharField(blank=True, max_length=100, null=True)),
                ('cardnum', models.CharField(blank=True, max_length=100, null=True)),
                ('bankcode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
