# Generated by Django 4.0.1 on 2022-11-16 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Applicant', '0018_paymentdetail_mihpayid'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_detail_flag', models.BooleanField(default=False)),
                ('other_detail_flag', models.BooleanField(default=False)),
                ('education_details_flag', models.BooleanField(default=False)),
                ('address_detail_flag', models.BooleanField(default=False)),
                ('bank_detail_flag', models.BooleanField(default=False)),
                ('document_upload_flag', models.BooleanField(default=False)),
                ('choice_filling_flag', models.BooleanField(default=False)),
                ('payment_flag', models.BooleanField(default=False)),
                ('final_submit_flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
