# Generated by Django 4.0.1 on 2022-11-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0021_alter_personaldetail_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='POSTED_SINCE',
            field=models.DateField(blank=True, null=True),
        ),
    ]
