# Generated by Django 4.0.1 on 2022-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0022_personaldetail_posted_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='DATE_OF_BIRTH',
            field=models.DateField(blank=True, null=True),
        ),
    ]
