# Generated by Django 4.0.1 on 2022-11-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0023_alter_personaldetail_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetail',
            name='POST_APPLIED_FOR',
            field=models.CharField(blank=True, choices=[('Asstistant Engineer/Manager - Technical/Distribution/Transmission/Genration(Electrical)', 'Asstistant Engineer/Manager - Technical/Distribution/Transmission/Genration(Electrical)'), ('Asstistant Engineer/Manager - Genration(Mechanical)', 'Asstistant Engineer/Manager - Genration(Mechanical)'), ('Asstistant Engineer/Manager (Civil)', 'Asstistant Engineer/Manager (Civil)'), ('Asstistant Engineer/Manager (IT)', 'Asstistant Engineer/Manager (IT)')], max_length=255, null=True),
        ),
    ]
