# Generated by Django 4.0.1 on 2022-11-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0024_alter_personaldetail_post_applied_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherdetail',
            name='COUNTRY',
            field=models.CharField(blank=True, choices=[('INDIAN', 'INDIAN'), ('OTHER', 'OTHER')], max_length=8, null=True),
        ),
    ]
