# Generated by Django 4.0.1 on 2022-11-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0025_otherdetail_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='DISABLITY_CERTIFICATE',
            field=models.FileField(blank=True, null=True, upload_to='PDF/DISABLITY_CERTIFICATE'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='INCOME_CERTIFICATE',
            field=models.FileField(blank=True, null=True, upload_to='PDF/INCOME_CERTIFICATE'),
        ),
    ]
