# Generated by Django 4.0.1 on 2022-11-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0026_documentupload_disablity_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicefilling',
            name='CHOICE_6',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_1',
            field=models.CharField(choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_2',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_3',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_4',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='choicefilling',
            name='CHOICE_5',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='CHOICE_1',
            field=models.CharField(choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='CHOICE_2',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='CHOICE_3',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='CHOICE_4',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='CHOICE_5',
            field=models.CharField(blank=True, choices=[('MPPKVVCL BHOPAL', 'MPPKVVCL BHOPAL'), ('MPPKVVCL JABALPUR', 'MPPKVVCL JABALPUR'), ('MPPKVVCL INDORE', 'MPPKVVCL INDORE'), ('MPTRANSCO', 'MPTRANSCO'), ('MPGENCO', 'MPGENCO'), ('MPPMCL', 'MPPMCL')], max_length=255, null=True),
        ),
    ]
