# Generated by Django 4.0.1 on 2022-11-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0027_choicefilling_choice_6_alter_choicefilling_choice_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldatatable',
            name='DISABLITY_CERTIFICATE',
            field=models.FileField(blank=True, null=True, upload_to='FINALPDF/DISABLITY_CERTIFICATE'),
        ),
        migrations.AddField(
            model_name='finaldatatable',
            name='EMPLOYMENT_TYPE',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Contractual', 'Contractual')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='finaldatatable',
            name='INCOME_CERTIFICATE',
            field=models.FileField(blank=True, null=True, upload_to='FINALPDF/INCOME_CERTIFICATE'),
        ),
        migrations.AddField(
            model_name='finaldatatable',
            name='POSTED_SINCE',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='AADHAAR_CARD',
            field=models.FileField(upload_to='FINALPDF/POST_GRADUATION'),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='CAST_CERTIFICATE',
            field=models.FileField(upload_to='FINALPDF/CAST_CERTIFICATE'),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='DEPARTMENTAL_NOC',
            field=models.FileField(blank=True, null=True, upload_to='FINALPDF/DEPARTMENTAL_NOC'),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='GATE_SCORECARD',
            field=models.FileField(upload_to='FINALPDF/GATE_SCORECARD'),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='GRADUATION_MARKSHEET',
            field=models.FileField(upload_to='FINALPDF/GRADUATION_MARKSHEET'),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='HIGH_SCHOOL',
            field=models.FileField(upload_to='FINALPDF/HIGH_SCHOOL'),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='HSSC',
            field=models.FileField(upload_to='FINALPDF/HSSC'),
        ),
        migrations.AlterField(
            model_name='finaldatatable',
            name='POST_GRADUATION',
            field=models.FileField(upload_to='FINALPDF/HIGH_SCHOOL'),
        ),
    ]
