# Generated by Django 4.0.1 on 2022-11-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicant', '0030_finaldatatable_ex_serviceman_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldatatable',
            name='Application_Number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
