from django import forms
# from .models import admin_block,Add_category,Postjobs ,TopFreelancer
# from ckeditor.widgets import CKEditorWidget
from .models import *


class openings_form(forms.ModelForm):
	Name_of_Exam=forms.CharField(required=False,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Enter Name of Exam'}))
	Advertisement=forms.CharField(required=False,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Enter Advertisement Number'}))
	Start_Date = forms.DateField(required=False,widget=forms.DateInput(attrs={'type': 'date','class':'form-control'}))
	End_Date = forms.DateField(required=False,widget=forms.DateInput(attrs={'type': 'date','class':'form-control'}))
	Advertisement_Pdf = forms.FileField(required=False,widget=forms.FileInput(attrs={'type': 'file','class':'form-control'}))
	BHOPAL_Electrical_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0,'value':0}))
	BHOPAL_Electrical_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Electrical_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Civil_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_It_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	BHOPAL_Mechanical_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Electrical_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Civil_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_It_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	JABALPUR_Mechanical_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_PWDID = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Electrical_TOTAL = forms.IntegerField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Civil_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_It_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	INDORE_Mechanical_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_ELECTRICAL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_CIVIL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_IT_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPGENCO_MECHANICAL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))

	MPTRANSCO_ELECTRICAL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_ELECTRICAL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))

	MPTRANSCO_CIVIL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_CIVIL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))

	MPTRANSCO_IT_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_IT_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))

	MPTRANSCO_MECHANICAL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPTRANSCO_MECHANICAL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))

	MPPMCL_ELECTRICAL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_ELECTRICAL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))

	MPPMCL_CIVIL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_CIVIL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))

	MPPMCL_IT_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_IT_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_URO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_URF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_STO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_STF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_SCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_SCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_OBCO = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_OBCF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_EWS = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_EWSF = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_PWDHI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_PWDOC = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_PWDVI = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_PWDID = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	MPPMCL_MECHANICAL_TOTAL = forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'0','value':0}))
	

	class Meta:
		model = AddVacancyPosition
		fields = '__all__'



# forms.CharField(widget=CKEditorWidget())
#CATE_CHOICES=[tuple([cate.category,cate.category])for cate in Add_category.objects.all()]
# class admin_block_form(forms.ModelForm):
# 	#title=forms.CharField(widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Title'}),label='Title')
# 	By=forms.CharField(widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'By'}),label='Title')
# 	#Description=forms.CharField(widget=CKEditorWidget({'class' :'form-control no-resize','placeholder':'Description'}),label='Description')
# 	Image=forms.ImageField(widget=forms.FileInput(attrs={'class':'dropIcon','accept':"image/*",'onchange':"preview_image(event)"}),label ='Upload Photo',)
# 	title=forms.CharField(widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Title'}),label='Title')
# 	#Select_Catogry=forms.CharField(widget=forms.Select( attrs={'class' :'form-control'},choices=CATE_CHOICES),label='Name')


	  
# 	class Meta:
# 		model = admin_block
# 		fields = {'title','By','Image','Description'}
# class category_form(forms.ModelForm):
# 	category=forms.CharField(widget=forms.TextInput( attrs={'class' :'form-control'}),label='Title')
# 	class Meta:
# 		model=Add_category
# 		fields='__all__'

# class postjobs_form(forms.ModelForm):
# 	ProjectName=forms.CharField(required=True,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'project Name'}),label='Project Name')
# 	Durations=forms.CharField(required=True,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Durations'}),label='Durations')
# 	skills=forms.CharField(required=True,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'skills'}),label='skills')
# 	CompanyName=forms.CharField(required=True,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Company Name'}),label='Company Name')
# 	payout=forms.CharField(required=True,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Amount'}),label='payout')
# 	location=forms.CharField(required=True,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'location'}),label='location')
# 	Image=forms.ImageField(required=True,widget=forms.FileInput(attrs={'class':'dropIcon','accept':"image/*",'onchange':"preview_image(event)"}),label ='Upload Photo',)
# 	Description=forms.CharField(required=True,widget=forms.Textarea( attrs={'class' :'form-control no-resize','placeholder':'Description'}),label='Description')
# 	class Meta:
# 		model=Postjobs 
# 		fields={'ProjectName','Durations','skills','CompanyName','payout','Description','location','Image'}


# class TopFreelancer_form(forms.ModelForm):
# 	FreelancerName=forms.CharField(required=True,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Freelancer Name'}),label='Project Name')
# 	Task=forms.CharField(required=True,widget=forms.TextInput( attrs={'class' :'form-control','placeholder':'Dailyprojects Completed '}),label='Company Name')
# 	city=forms.CharField(widget=forms.TextInput(attrs={'class' :'form-control','placeholder':'city '}),label='city')
# 	collage=forms.CharField(widget=forms.TextInput(attrs={'class' :'form-control','placeholder':'college '}),label='college')
# 	class Meta:
# 		model =TopFreelancer
# 		fields={'FreelancerName','Task','city','collage'}
