# Generated by Django 4.0.1 on 2022-08-05 06:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Enter data', max_length=255)),
                ('sub_title', models.TextField()),
                ('Description', models.TextField(default='add Description')),
                ('title1', models.TextField(default='enter title 1')),
                ('sub_title1', models.TextField(default='enter sub_title 1')),
                ('L1FB_Header', models.TextField(default='enter sub_title 1')),
                ('L1FB_Details', models.TextField(default='enter sub_title 1')),
                ('L1SB_Header', models.TextField(default='enter sub_title 1')),
                ('L1SB_Details', models.TextField(default='enter sub_title 1')),
                ('L2FB_Header', models.TextField(default='enter sub_title 1')),
                ('L2FB_Details', models.TextField(default='enter sub_title 1')),
                ('L2SB_Header', models.TextField(default='enter sub_title 1')),
                ('L2SB_Details', models.TextField(default='enter sub_title 1')),
                ('L3FB_Header', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L3FB_Details', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L3SB_Header', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L3SB_Details', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L4FB_Header', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L4FB_Details', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L4SB_Header', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L4SB_Details', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L5FB_Header', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L5FB_Details', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L5SB_Header', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L5SB_Details', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L6FB_Header', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L6FB_Details', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L6SB_Header', models.TextField(blank=True, default='enter sub_title 1', null=True)),
                ('L6SB_Details', models.TextField(blank=True, default='enter sub_title 1', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('create_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='admin_block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('By', models.CharField(max_length=255)),
                ('Description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('Select_Catogry', models.CharField(default=False, max_length=255)),
                ('Image', models.ImageField(upload_to='media/Images')),
                ('date', models.DateField(auto_now=True)),
                ('status', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Banner_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Add Title here', max_length=255)),
                ('Sub_Title', models.CharField(default='add Sub_Title here', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bussines_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255)),
                ('Description', models.TextField(default='Description')),
            ],
        ),
        migrations.CreateModel(
            name='footer_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Postjobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectName', models.CharField(max_length=255)),
                ('CompanyName', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('payout', models.CharField(max_length=255)),
                ('Durations', models.CharField(max_length=255)),
                ('Description', models.TextField(default='')),
                ('location', models.CharField(default=True, max_length=255)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/Images/Postjobs')),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Social_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(default='enter facebook link', max_length=255)),
                ('instagram', models.CharField(default='enter instagram link', max_length=255)),
                ('linkedin', models.CharField(default='enter linkedin link', max_length=255)),
                ('twitter', models.CharField(default='enter twitter link', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopFreelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FreelancerName', models.CharField(max_length=255)),
                ('Task', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('collage', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
