# Generated by Django 4.0.1 on 2022-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitmentadmin', '0002_addvacancyposition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_EWS',
            new_name='MPGENCO_CIVIL_EWS',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_EWSF',
            new_name='MPGENCO_CIVIL_EWSF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_OBCF',
            new_name='MPGENCO_CIVIL_OBCF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_OBCO',
            new_name='MPGENCO_CIVIL_OBCO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_PWDHI',
            new_name='MPGENCO_CIVIL_PWDHI',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_PWDID',
            new_name='MPGENCO_CIVIL_PWDID',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_PWDOC',
            new_name='MPGENCO_CIVIL_PWDOC',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_PWDVI',
            new_name='MPGENCO_CIVIL_PWDVI',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_SCF',
            new_name='MPGENCO_CIVIL_SCF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_SCO',
            new_name='MPGENCO_CIVIL_SCO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_STF',
            new_name='MPGENCO_CIVIL_STF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_STO',
            new_name='MPGENCO_CIVIL_STO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_TOTAL',
            new_name='MPGENCO_CIVIL_TOTAL',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_URF',
            new_name='MPGENCO_CIVIL_URF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPGENCO_URO',
            new_name='MPGENCO_CIVIL_URO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_EWS',
            new_name='MPGENCO_ELECTRICAL_EWS',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_EWSF',
            new_name='MPGENCO_ELECTRICAL_EWSF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_OBCF',
            new_name='MPGENCO_ELECTRICAL_OBCF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_OBCO',
            new_name='MPGENCO_ELECTRICAL_OBCO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_PWDHI',
            new_name='MPGENCO_ELECTRICAL_PWDHI',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_PWDID',
            new_name='MPGENCO_ELECTRICAL_PWDID',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_PWDOC',
            new_name='MPGENCO_ELECTRICAL_PWDOC',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_PWDVI',
            new_name='MPGENCO_ELECTRICAL_PWDVI',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_SCF',
            new_name='MPGENCO_ELECTRICAL_SCF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_SCO',
            new_name='MPGENCO_ELECTRICAL_SCO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_STF',
            new_name='MPGENCO_ELECTRICAL_STF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_STO',
            new_name='MPGENCO_ELECTRICAL_STO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_TOTAL',
            new_name='MPGENCO_ELECTRICAL_TOTAL',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_URF',
            new_name='MPGENCO_ELECTRICAL_URF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPPMCL_URO',
            new_name='MPGENCO_ELECTRICAL_URO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_EWS',
            new_name='MPGENCO_IT_EWS',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_EWSF',
            new_name='MPGENCO_IT_EWSF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_OBCF',
            new_name='MPGENCO_IT_OBCF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_OBCO',
            new_name='MPGENCO_IT_OBCO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_PWDHI',
            new_name='MPGENCO_IT_PWDHI',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_PWDID',
            new_name='MPGENCO_IT_PWDID',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_PWDOC',
            new_name='MPGENCO_IT_PWDOC',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_PWDVI',
            new_name='MPGENCO_IT_PWDVI',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_SCF',
            new_name='MPGENCO_IT_SCF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_SCO',
            new_name='MPGENCO_IT_SCO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_STF',
            new_name='MPGENCO_IT_STF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_STO',
            new_name='MPGENCO_IT_STO',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_TOTAL',
            new_name='MPGENCO_IT_TOTAL',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_URF',
            new_name='MPGENCO_IT_URF',
        ),
        migrations.RenameField(
            model_name='addvacancyposition',
            old_name='MPTRANSCO_URO',
            new_name='MPGENCO_IT_URO',
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPGENCO_MECHANICAL_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_CIVIL_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_ELECTRICAL_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_IT_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPPMCL_MECHANICAL_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_CIVIL_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_ELECTRICAL_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_IT_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_EWS',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_EWSF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_OBCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_OBCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_PWDHI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_PWDID',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_PWDOC',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_PWDVI',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_SCF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_SCO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_STF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_STO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_TOTAL',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_URF',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='MPTRANSCO_MECHANICAL_URO',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
