# Generated by Django 4.0.1 on 2022-11-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruitmentadmin', '0003_rename_mpgenco_ews_addvacancyposition_mpgenco_civil_ews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addvacancyposition',
            name='Vacancy_For_Bhopal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='Vacancy_For_Indore',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='Vacancy_For_Jabalpur',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='Vacancy_For_Mpgenco',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='Vacancy_For_Mppmcl',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='addvacancyposition',
            name='Vacancy_For_Mptransco',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
